apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-web-app
  name: todo-web-app
  namespace: default
spec:
  ports:
  - nodePort: 30005
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: todo-web-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.232.142.216
