apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webapp
    version: v1
  name: webapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      containers:
      - image: vynaidudocker/hello-world-rest-api:0.0.1
        imagePullPolicy: IfNotPresent
        name: hello-world-rest-api
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: default
spec:
  ports:
  - nodePort: 31458
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
    version: v1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.224.118.244
